#!/bin/sh
set -ue

declare \
  CF_STACK= \
  CF_CHANGE_SET=`date +%s|md5sum|cut -c -7` \
  CF_ACTION= \
  TEMPLATE_BODY= \
  PARAMETERS_BODY=

while [[ $# -gt 0 ]]
do
  case $1 in
    deploy|output|status|diff|changes|apply)
      CF_ACTION=$1
      shift
      ;;

    --stack-name|--stack|-s)
      CF_STACK=$2
      shift 2 || exit 2
      ;;

    --change-set-name|--change|-c)
      CF_CHANGE_SET=$2
      shift 2 || exit 2
      ;;

    --template-body|--template|-t)
      TEMPLATE_BODY=$2
      shift 2 || exit 2
      ;;

    --parameters|-p)
      PARAMETERS_BODY=$2
      shift 2 || exit 2
      ;;

    --help|-h)
      cat <<EOF
Help $0

Action:
    deploy|output|status|diff|changes|apply)

Flags:
    --stack-name|--stack|-s)
    --change-set-name|--change|-c)
    --template-body|--template|-t)
    --parameters|-p)
    --help|-h)
EOF
      exit 0
      ;;

    *)
      exit 1
      ;;
  esac
done

cloudformation__deploy() {
  [[ -n "${CF_STACK}" ]]
  [[ -f "${TEMPLATE_BODY}" ]]

  if aws cloudformation get-template --stack-name "${CF_STACK}" > /dev/null 2> /dev/null
  then
    aws cloudformation update-stack \
      --stack-name "${CF_STACK}" \
      `[[ -z ${PARAMETERS_BODY} ]] || echo --parameters file://${PARAMETERS_BODY}` \
      --template-body "file://${TEMPLATE_BODY}" \
      --capabilities CAPABILITY_IAM \
      --output text \
      || exit 0

    aws cloudformation wait stack-update-complete \
      --stack-name "${CF_STACK}" \
      --output text
  else
    aws cloudformation create-stack \
      --stack-name "${CF_STACK}" \
      `[[ -z ${PARAMETERS_BODY} ]] || echo --parameters "file://${PARAMETERS_BODY}"` \
      --template-body "file://${TEMPLATE_BODY}" \
      --capabilities CAPABILITY_IAM \
      --on-failure DELETE \
      --output text

    aws cloudformation wait stack-create-complete \
      --stack-name "${CF_STACK}" \
      --output text
  fi
}

cloudformation__diff() {
  [[ -n "${CF_STACK}" ]]
  [[ -n "${CF_CHANGE_SET}" ]]
  [[ -f "${TEMPLATE_BODY}" ]]

  aws cloudformation create-change-set \
    --change-set-name "${CF_STACK}-${CF_CHANGE_SET}" \
    --stack-name "${CF_STACK}" \
    `[[ -z ${PARAMETERS_BODY} ]] || echo --parameters "file://${PARAMETERS_BODY}"` \
    --template-body "file://${TEMPLATE_BODY}" \
    --capabilities CAPABILITY_IAM \
    --output text
}

cloudformation__changes() {
  [[ -n "${CF_STACK}" ]]

  aws cloudformation list-change-sets \
    --stack-name "${CF_STACK}" \
    --query 'Summaries[].[ChangeSetName, Status]' \
    --output text
}

cloudformation__apply() {
  [[ -n "${CF_STACK}" ]]
  [[ -n "${CF_CHANGE_SET}" ]]

  aws cloudformation execute-change-set \
    --change-set-name "${CF_STACK}-${CF_CHANGE_SET}" \
    --stack-name "${CF_STACK}" \
    --output text

  aws cloudformation wait stack-update-complete \
    --stack-name "${CF_STACK}" \
    --output text
}

cloudformation__output() {
  [[ -n "${CF_STACK}" ]]

  aws cloudformation describe-stacks \
    --stack-name "${CF_STACK}" \
    --query "Stacks[].Outputs[].[OutputKey, OutputValue]" \
    --output text
}

cloudformation__status() {
  aws cloudformation describe-stacks \
    --query "Stacks[].[StackName, StackStatus, StackStatusReason]" \
    --output text
}

[[ -n "${CF_ACTION}" ]]
cloudformation__${CF_ACTION}
