#!/bin/sh
set -ue

CF_STACK="$(pwd|xargs basename)"
CF_CHANGE_SET="$(date +%s|md5sum|cut -c -7)"
CF_ACTION=""
CF_OUTPUT="--output=text"
CF_DEBUG=""
TEMPLATE_BODY=cloudformation.template
PARAMETERS_BODY=""
CF_MAX_ITEM=10

while [ $# -gt 0 ]
do
  case $1 in
    deploy)
      CF_ACTION=deploy
      shift
      ;;
    delete)
      CF_ACTION=delete
      shift
      ;;

    output|o)
      CF_ACTION=output
      shift
      ;;

    status|s)
      CF_ACTION=status
      shift
      ;;

    apply|a)
      CF_ACTION=apply
      shift
      ;;

    changes|c)
      CF_ACTION=changes
      shift
      ;;

    patch|p)
      CF_ACTION=patch
      shift
      ;;

    diff|d)
      CF_ACTION=diff
      shift
      ;;

    logs|l)
      CF_ACTION=logs
      shift
      ;;

    help|h)
      CF_ACTION=help
      shift
      ;;

    --stack-name|--stack|-s)
      CF_STACK=$2
      shift 2 || exit 2
      ;;

    --change-set-name|--change|-c)
      CF_CHANGE_SET=$2
      shift 2 || exit 2
      ;;

    --template-body|--template|-t)
      TEMPLATE_BODY=$2
      if [ -f "${TEMPLATE_BODY}" ]
      then TEMPLATE_BODY="file://${TEMPLATE_BODY}"
      fi
      shift 2 || exit 2
      ;;

    --parameters|-p)
      PARAMETERS_BODY=$2
      if [ -f "${PARAMETERS_BODY}" ]
      then PARAMETERS_BODY="file://${PARAMETERS_BODY}"
      fi
      shift 2 || exit 2
      ;;

    --max-item|--item|-i)
      CF_MAX_ITEM=$2
      shift 2 || exit 2
      ;;


    --debug|-d)
      CF_DEBUG="--debug"
      set -x
      shift
      ;;

    *)
      exit 1
      ;;
  esac
done

cloudformation__deploy() {
  [ -n "${CF_STACK}" ]
  [ -n "${TEMPLATE_BODY}" ]

  if aws cloudformation get-template --stack-name "${CF_STACK}" > /dev/null 2> /dev/null
  then
    aws cloudformation update-stack \
      --stack-name "${CF_STACK}" \
      "$([ -z "${PARAMETERS_BODY}" ] || echo --parameters)" "${PARAMETERS_BODY}" \
      --template-body "${TEMPLATE_BODY}" \
      --capabilities CAPABILITY_IAM \
      "${CF_DEBUG}" "${CF_OUTPUT}" || exit 0

    aws cloudformation wait stack-update-complete \
      --stack-name "${CF_STACK}" \
      "${CF_DEBUG}" "${CF_OUTPUT}"
  else
    aws cloudformation create-stack \
      --stack-name "${CF_STACK}" \
      "$([ -z "${PARAMETERS_BODY}" ] || echo --parameters)" "${PARAMETERS_BODY}" \
      --template-body "${TEMPLATE_BODY}" \
      --capabilities CAPABILITY_IAM \
      --on-failure DELETE \
      "${CF_DEBUG}" "${CF_OUTPUT}"

    aws cloudformation wait stack-create-complete \
      --stack-name "${CF_STACK}" \
      "${CF_DEBUG}" "${CF_OUTPUT}"
  fi
}

cloudformation__delete() {
  [ -n "${CF_STACK}" ]

  aws cloudformation delete-stack \
    --stack-name "${CF_STACK}" \
    "${CF_DEBUG}" "${CF_OUTPUT}"
}

cloudformation__patch() {
  [ -n "${CF_STACK}" ]
  [ -n "${CF_CHANGE_SET}" ]
  [ -n "${TEMPLATE_BODY}" ]

  aws cloudformation create-change-set \
    --change-set-name "${CF_STACK}-${CF_CHANGE_SET}" \
    --stack-name "${CF_STACK}" \
    "$([ -z "${PARAMETERS_BODY}" ] || echo --parameters)" "${PARAMETERS_BODY}" \
    --template-body "${TEMPLATE_BODY}" \
    --capabilities CAPABILITY_IAM \
    "${CF_DEBUG}" "${CF_OUTPUT}"
}

cloudformation__diff() {
  [ -n "${CF_STACK}" ]
  [ -n "${CF_CHANGE_SET}" ]

  aws cloudformation describe-change-set \
    --change-set-name "${CF_STACK}-${CF_CHANGE_SET}" \
    --stack-name "${CF_STACK}" \
    --query "Changes[].[ResourceChange.[Action,ResourceType,LogicalResourceId]]" \
    "${CF_DEBUG}" "${CF_OUTPUT}"
}

cloudformation__changes() {
  [ -n "${CF_STACK}" ]

  aws cloudformation list-change-sets \
    --stack-name "${CF_STACK}" \
    --query 'Summaries[].[ChangeSetName, Status]' \
    "${CF_DEBUG}" "${CF_OUTPUT}"
}

cloudformation__apply() {
  [ -n "${CF_STACK}" ]
  [ -n "${CF_CHANGE_SET}" ]

  aws cloudformation execute-change-set \
    --change-set-name "${CF_STACK}-${CF_CHANGE_SET}" \
    --stack-name "${CF_STACK}" \
    "${CF_DEBUG}" "${CF_OUTPUT}"

  aws cloudformation wait stack-update-complete \
    --stack-name "${CF_STACK}" \
    "${CF_DEBUG}" "${CF_OUTPUT}"
}

cloudformation__output() {
  [ -n "${CF_STACK}" ]

  aws cloudformation describe-stacks \
    --stack-name "${CF_STACK}" \
    --query "Stacks[].Outputs[].[OutputKey, OutputValue]" \
    "${CF_DEBUG}" "${CF_OUTPUT}"
}

cloudformation__status() {
  aws cloudformation describe-stacks \
    --query "Stacks[].[StackName, StackStatus, StackStatusReason]" \
    "${CF_DEBUG}" "${CF_OUTPUT}"
}


cloudformation__logs() {
  aws cloudformation describe-stack-events \
    --stack-name "${CF_STACK}" \
    --max-item "${CF_MAX_ITEM}" \
    --query "StackEvents[].[Timestamp,ResourceStatus,LogicalResourceId,ResourceStatusReason]" \
    "${CF_DEBUG}" "${CF_OUTPUT}"
}

cloudformation__help() {
  cat <<EOF
  Usage: $0
  ---

  Actions
  ---
$(awk '/^ +[^- $$].+)$/{print}' "$0")

  Flags
  ---
$(awk '/^ +-.+)$/{print}' "$0")
EOF
}

[ -n "${CF_ACTION}" ]
cloudformation__${CF_ACTION}
