#!/bin/bash

declare __v__profile="default"
declare __v__credentials="${HOME}/.aws/credentials"

while [[ $# -gt 0 ]]
do
  case $1 in
    --profile|-p)
      __v__profile=$2
      shift 2 || exit 2
      ;;
    --credentials|-c)
      __v__credentials=$2
      shift 2 || exit 2
      ;;
    *)
      __v__profile=$1
      shift
      ;;
  esac
done

awk -v profile="${__v__profile}" \
  '$1=="["profile"]"{view=1;next}$1~/^\[/{view=0;next}view==1{print"export",toupper($1)"="$3";"}' \
  "${__v__credentials}"
