#!/bin/bash
set -ue

declare \
  __v__profile="default" \
  __v__credentials="${HOME}/.aws/credentials" \
  __v__config="${HOME}/.aws/config"

while [[ $# -gt 0 ]]
do
  case $1 in
    --profile|-p)
      __v__profile=$2
      shift 2 || exit 2
      ;;

    --credentials|-c)
      __v__credentials=$2
      shift 2 || exit 2
      ;;

    *)
      __v__profile=$1
      shift
      ;;
  esac
done

awk -v profile="${__v__profile}" \
  '$1=="["profile"]"{view=1;next}$1~/^\[/{view=0;next}view==1{print"export",toupper($1)"=\""$3"\";"}' \
  "${__v__credentials}"

awk -v profile="${__v__profile}" \
  '$1=="[profile "profile"]"{view=1;next}$1~/^\[/{view=0;next}view==1&&/^region/{print"export","AWS_"toupper($1)"=\""$3"\";"}' \
  "${__v__config}"
